name: CI/CD Pipeline

on:
  push:
     branches:
         - main
  pull_request:
      branches:
          -main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Preuzimanje koda iz Git-a
        uses: actions/checkout@v4

      - name: 2. Sintaksna provera Dockerfile-a (Linting)
        uses: hadolint/hadolint-action@v3.1.0
        with:
            dockerfile: app/Dockerfile
        
      - name: 3. Provera Helm Chart-a (Helm Lint)
        run: |
          helm lint helm/app-chart
      
      - name: 4. Pokretanje i testiranje Docker slike lokalno
        run: |
          cd app
          docker build -t moj-devops-app:test .
          docker run -d -p 5000:5000 --name test-app moj-devops-app:test
          sleep 3
          curl http://localhost:5000/healthz | grep OK
          docker stop test-app

      - name: 5. Prijava na Github Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 6. Izgradnja i slanje Docker slike na registar
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            ghcr.io/goran148/moj-devops-app:latest
            ghcr.io/goran148/moj-devops-app:${{ github.sha }}